title: Irene N
logo: irenen.png
description: Hii there!
#show_downloads : True
theme: jekyll-theme-minimal

position: Ph.D. Student
affiliation: Your Affiliation
email: nohar003 (at) umn (dot) edu
linkedin: https://www.linkedin.com/in/irenenoharinaivo

# Links 
# google_scholar: https://scholar.google.com/
# cv_link: assets/files/curriculum_vitae.pdf
#github_link: https://github.com/


